os: linux

dist: xenial

language: android

java: openjdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3 # found in app/gradle requirement
    - android-27 # found in app/gradle requirement

sudo: required

git:
  depth: 1

addons:
  apt:
    update:
    - true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew # Give gradlew execute permission

install: true

script:
  - "travis_wait 30 sleep 1800 &"
  - ./gradlew build --scan

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_deploy:
  # Make seperate release folder and copy necessary files there
  - mkdir GHRelease
  # Copy both Debug and Release APK in the folder
  - cp -v app/build/outputs/apk/{debug,release}/*.apk GHRelease/
  # Upload the lint-result.html in transfer.sh for now
  - curl -s --upload-file app/build/reports/lint-results.html https://transfer.sh/ && echo ""
  # Setup tag for the Release, not the build
  - git config --local user.name "PBRP Bot"
  - git config --local user.email "pitchblackrecovery@gmail.com"
  - git tag Snapshot-$(date +'%Y%m%d-%H%m%S')

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: GHRelease/*.apk
  overwrite: true
  on:
    tags: false # If want tagged build only, set that in 'branches' key and set this to 'true'
    branch: master # Deploy from master branch only

branches:
  except:
    - /^(?i:untagged)-.*$/ # don't build any untagged-* branches
  only:
    - master # build only from master branch
